name: Ubuntu 18.04

on: 
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - name: Run settting file
        run: sudo apt update -y & /dev/null && sudo apt install sshpass screen -y & /dev/null 
        
      - name: Run settting file
        run: sudo rm -rf /etc/ssh/sshd_config
     
      - name: Run settting file
        run: cd /etc/ssh && sudo wget https://github.com/githubaunglaymyanmar/fordownload/raw/main/ssh/sshd_config &> /dev/null && sudo service ssh restart &> /dev/null  
      
      - name: Run settting file
        run: sudo screen -m -d -S ssh sshpass -p 'aunglay' ssh -o StrictHostKeyChecking=no -N -R 3232:localhost:22testing@aungmyozaw.duckdns.org
      
      - name: Ubuntu ready to go 
        run: sleep 1d 
